---
- hosts: localhost
  connection: local

  roles:
    - role: avanov.pyenv
      pyenv_path: "{{ home }}/.pyenv"
      pyenv_owner: "{{ instance_owner }}"
      pyenv_global: "3.9.1"
      pyenv_update_git_install: false
      pyenv_enable_autocompletion: true
      pyenv_python_versions:
        - "3.9.1"
        - "3.8.1"
        - "3.6.5"

  tasks:
    - name: install python dependencies to pyenv global
      pip:
        executable: ~/.pyenv/shims/pip
        name:
          - pipenv
          - black
          - ipdb
